version: '2.1'

services:
  personal-blog:
    image: personal-blog
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongodb_personal-blog:27017/personal-blog_dev
      - SECRET_KEY='<CHANGETHIS>'
  mongodb:
    image: mongo:latest
    container_name: "mongodb_personal-blog"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null